delete from animals_type_animal;
delete from animals_visit_locations;
delete from type_animal;
AlTER SEQUENCE type_animal_type_id_seq RESTART with 1;
delete from visit_locations;
AlTER SEQUENCE visit_locations_visit_location_id_seq RESTART with 1;
delete from animals;
AlTER SEQUENCE animals_animal_id_seq RESTART with 1;
delete from users;
AlTER SEQUENCE users_user_id_seq RESTART with 1;
delete from locations;
AlTER SEQUENCE locations_location_id_seq RESTART with 1;
delete from areas;
AlTER SEQUENCE areas_area_id_seq RESTART with 1;
